name: Gradle Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Version to release'
      newVersion:
        description: 'Version to set after release'

jobs:
  release:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: git config --global user.email "olivier.lemerdy+gha@kry.se"
      - run: git config --global user.name "${{ github.actor }}"
      - name: Release with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: release -Prelease.useAutomaticVersion=true -Prelease.releaseVersion=${{ github.event.inputs.releaseVersion }} -Prelease.newVersion=${{ github.event.inputs.newVersion }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}